---
title: "R_analysis"
output: html_notebook
---

# Set working environment path here:
```{r}
setwd("/home/vignesh/Data/old_ubuntu/YASARA-log-file-analysis")
```

# install packages
```{r}
install.packages("ggplot2")
install.packages("dplyr")
install.packages("reshape")
```

# load libraries
```{r}
library(ggplot2)
library(dplyr)
library(reshape)
```

# Scatter plot of contacts
```{r}
rm(list=ls())
# modify the path to the folder and the filename in the lines below to display a line plot for that file
path_to_dir = "ecoli_bamA_mosselii_llpA1/analysis/non_zero_contacts_tables/"
filename = "contacts_of_pdb_9.csv"

path_to_file = paste(path_to_dir, filename, sep="")
scatter_plot_table <- read.csv(path_to_file, sep="\t")
head(data)


scatter_plot_table <- scatter_plot_table %>%
  mutate(X0 = make.unique(as.character(X0)))


scatter_plot_table$X0 <- factor(scatter_plot_table$X0, levels = scatter_plot_table$X0)


ggplot(scatter_plot_table, aes(x = X0, y = X1, group = 1)) +
  geom_point( alpha = 0.5) +
  labs(x = "Receptor + Binding Protein Residues", y = "Contacts", title = "Scatter Plot of Contacts vs Binding pairs") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size=5)) # adjust the size of your x axis labels here


ggsave(
  'plot9.png', # modify the file name of the plot here
  path = path_to_dir, 
  plot=last_plot(),
  dpi = 1000
)
```

# Comparing interactions_table of two datasets:
```{r}
rm(list=ls())

# initializing variables:
sample_1_data <- read.csv("ecoli_bamA_mosselii_llpA1/analysis/interactions_table.csv", sep="\t")
sample_2_data <- read.csv("input_files/interactions_table.csv", sep="\t")

sample_1_contacts <- as.numeric(unlist(sample_1_data['Contacts.across.PDBs']))
sample_2_contacts <- as.numeric(unlist(sample_2_data['Contacts.across.PDBs']))

sample_1_hbonds <- as.numeric(unlist(sample_1_data['h_bonds']))
sample_2_hbonds <- as.numeric(unlist(sample_2_data['h_bonds']))

sample_1_hydrophobic <- as.numeric(unlist(sample_1_data['Hydrophobic']))
sample_2_hydrophobic <- as.numeric(unlist(sample_2_data['Hydrophobic']))

sample_1_ionic <- as.numeric(unlist(sample_1_data['Ionic']))
sample_2_ionic <- as.numeric(unlist(sample_2_data['Ionic']))

sample_1_cationpi <- as.numeric(unlist(sample_1_data['CationPi']))
sample_2_cationpi <- as.numeric(unlist(sample_2_data['CationPi']))

sample_1_pipi <- as.numeric(unlist(sample_1_data['PiPi']))
sample_2_pipi <- as.numeric(unlist(sample_2_data['PiPi']))

# Test to check if samples don't follow a normal distribution
shapiro.test(sample_2_contacts)
shapiro.test(sample_1_contacts)
shapiro.test(sample_2_hbonds)
shapiro.test(sample_1_hbonds)
shapiro.test(sample_2_hydrophobic)
shapiro.test(sample_1_hydrophobic)
shapiro.test(sample_2_ionic)
shapiro.test(sample_1_ionic)
shapiro.test(sample_2_cationpi)
shapiro.test(sample_1_cationpi)
shapiro.test(sample_2_pipi)
shapiro.test(sample_1_pipi)

# Since data is not normally distributed:
wilcox.test(sample_2_contacts, sample_1_contacts)

wilcox.test(sample_2_hbonds, sample_1_hbonds)

wilcox.test(sample_2_hydrophobic, sample_1_hydrophobic)

wilcox.test(sample_2_ionic, sample_1_ionic)

wilcox.test(sample_2_cationpi, sample_1_cationpi)

wilcox.test(sample_2_pipi, sample_1_pipi)


mean(sample_2_contacts)
mean(sample_1_contacts)

mean(sample_2_hbonds)
mean(sample_1_hbonds)

mean(sample_2_hydrophobic)
mean(sample_1_hydrophobic)

mean(sample_2_ionic)
mean(sample_1_ionic)

mean(sample_2_cationpi)
mean(sample_1_cationpi)

mean(sample_2_pipi)
mean(sample_1_pipi)


#
# When lists don't include zeros:
sample_2_contacts <- sample_2_contacts[sample_2_contacts != 0]
sample_1_contacts <- sample_1_contacts[sample_1_contacts != 0]

wilcox.test(sample_2_contacts, sample_1_contacts)
```

